version: 0.2

phases:
  pre_build:
    commands: |
      echo Getting Nessus package
      $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      aws s3 cp s3://${BUCKET}/Nessus-8.10.0-ubuntu1110_amd64.deb Nessus.deb --no-progress
  build:
    commands: |
      echo Build started on `date`
      set -e
      IMAGE_TAG=$(cat version)
      docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg BUCKET=$BUCKET .
      echo Build completed on `date`

      echo Testing $IMAGE_REPO_NAME:$IMAGE_TAG
      docker run -e LICENSE=XXXX-XXXX-XXXX-XXXX-XXXX $IMAGE_REPO_NAME:$IMAGE_TAG /usr/bin/test.sh
      
      echo Pushing the Docker image with tags of $IMAGE_TAG and $CODEBUILD_RESOLVED_SOURCE_VERSION ...
      docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      docker push $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_URL:$IMAGE_TAG
      docker push $IMAGE_REPO_URL:$IMAGE_TAG
      
      echo Deploying $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION to $CLUSTER
      aws eks update-kubeconfig --name "$CLUSTER"
      k8s/deploy.sh $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
