version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -t logindotgov/nessus:$CIRCLE_BRANCH -t logindotgov/nessus:$CIRCLE_SHA1 .
      - run: |
          # run a test to make sure that nessus works!
          docker run -e LICENSE=XXXX-XXXX-XXXX-XXXX-XXXX logindotgov/nessus:$CIRCLE_BRANCH /usr/bin/test.sh
      - run: |
          # push it to the repo if the test passes
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push logindotgov/nessus:$CIRCLE_SHA1
          docker push logindotgov/nessus:$CIRCLE_BRANCH
          if [ "$CIRCLE_BRANCH" = "master" ] ; then
            docker push logindotgov/nessus:latest
          fi
workflows:
  version: 2
  release:
    jobs:
      - build
