apiVersion: v1
kind: PersistentVolume
metadata:
  name: nessus-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/nessus"

